name: Dependant workflow

on:
  repository_dispatch:
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.client_payload.message }}"