name: Hello

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  greeting:

  strategy:
    fail-fast: true
    matrix: 
      env: [
        { name: 'development' },
        { name: 'production' }
      ]

    runs-on: ubuntu-latest
    steps:
    - name: Get the repo
      uses: actions/checkout@v2

    - name: Load the environment
      uses: xom9ikk/dotenv@v1
      with:
        mode: ${{ matrix.env.name }}

    - name: Say something nice
      run: |
        echo "Hello ${{ env.MSG }}"
