name: Hello

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 21 * * 0'

jobs:
  hello:
    name: "Say hello 👋"
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run: |
        echo "Hello ${{github.event.inputs.name}}"
  
  build-in-container:
    name: "Build in 🐳"
    needs: hello
    runs-on: ubuntu-latest
    container:
      image: 12.21.0-stretch
      env:
        NODE_ENV: development
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build --if-present
        
  build-in-vm:
    name: "Build 🚧:"
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build --if-present

  build-with-cache:
    name: "Build with 📚"
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        
  deploy:
    name: "Deploy 🚀"
    runs-on: ubuntu-latest
    needs: 
      - build-with-cache
      - build-in-container 
      - build-in-vm
    outputs:
      production_message: ${{ steps.share.outputs.production_message }}
      development_message: ${{ steps.share.outputs.development_message }}
      staging_message: ${{ steps.share.outputs.staging_message }}

    strategy:
      fail-fast: true
      matrix: 
        env: [
          { name: 'development' },
          { name: 'staging' },
          { name: 'production' }
        ]
    
    environment: 
      name: ${{ matrix.env.name }}
      
    steps:
    - name: Get the repo
      uses: actions/checkout@v2

    - name: Load the environment
      uses: xom9ikk/dotenv@v1
      with:
        mode: ${{ matrix.env.name }}

    - name: Say something nice
      run: |
        echo "::group::My messages in a group"
        echo "Hello ${{ env.MSG }} from $${github.event.inputs.name}}. Here's a secret ${{ secrets.SECRET_MESSAGE }}"
        echo "::endgroup::"

    - name: Share something nice
      id: share
      run: |
        echo "::set-output name=${{ matrix.env.name }}_message::${{ env.MSG }}"
   
  goodbye:
    name: "Bye 🖖"
    runs-on: ubuntu-latest
    needs: 
      - deploy
    steps:
    - name: Retrieve something nice
      run: |
        echo "::warning ::${{ needs.deploy.outputs.production_message }}"
  