name: Hello

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run: |
        echo "Hello $${github.event.inputs.name}}"
        
  greeting:
    runs-on: ubuntu-latest
    
    outputs:
      production_message: ${{ steps.share.outputs.production_message }}
      development_message: ${{ steps.share.outputs.development_message }}
      staging_message: ${{ steps.share.outputs.staging_message }}

    strategy:
      fail-fast: true
      matrix: 
        env: [
          { name: 'development' },
          { name: 'staging' },
          { name: 'production' }
        ]
    
    environment: 
      name: ${{ matrix.env.name }}
      
    steps:
    - name: Get the repo
      uses: actions/checkout@v2

    - name: Load the environment
      uses: xom9ikk/dotenv@v1
      with:
        mode: ${{ matrix.env.name }}

    - name: Say something nice
      run: |
        echo "::group::My messages in a group"
        echo "Hello ${{ env.MSG }} from $${github.event.inputs.name}}. Here's a secret ${{ secrets.SECRET_MESSAGE }}"
        echo "::endgroup::"
        echo "::warning ::${{ env.MSG }}"

    - name: Share something nice
      id: share
      run: |
        echo "::set-output name=${{ matrix.env.name }}_message::${{ env.MSG }}"
   
  goodbye:
    runs-on: ubuntu-latest
    needs: 
      - greeting
    steps:
    - name: Retrieve something nice
      run: |
        echo "${{ needs.greeting.outputs.production_message }}"
   
