name: Hello

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix: 
        env: [
          { name: 'development' },
          { name: 'production' }
        ]
    
    environment: 
      name: ${{ matrix.env.name }}
      
    steps:
    - name: Get the repo
      uses: actions/checkout@v2

    - name: Load the environment
      uses: xom9ikk/dotenv@v1
      with:
        mode: ${{ matrix.env.name }}

    - name: Say something nice
      run: |
        echo "Hello ${{ env.MSG }}"
