name: Hello

on: 
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix: 
        env: [
          { name: 'development' },
          { name: 'staging' },
          { name: 'production' }
        ]
    
    environment: 
      name: ${{ matrix.env.name }}
      
    steps:
    - name: Get the repo
      uses: actions/checkout@v2

    - name: Load the environment
      uses: xom9ikk/dotenv@v1
      with:
        mode: ${{ matrix.env.name }}

    - name: Say something nice
      run: |
        echo "::group::My messages in a group"
        echo "Hello ${{ env.MSG }}. Here's a secret ${{ secrets.SECRET_MESSAGE }}"
        echo "::endgroup::"
        echo "::warning ::${{ env.MSG }}"

    - name: Share something nice
      run: |
        echo "::set-output name=${{ matrix.env.name }}::${{ env.MSG }}"
   
  goodbye:
    runs-on: ubuntu-latest
    needs: 
      - greeting  
    steps:
      - name: Share something nice
      run: |
        echo "${{ needs.greeting.production }}"
   
